version: '3.9'

networks:
    backend:
        driver: bridge
        ipam:
            config:
                - subnet: 192.100.100.0/24

services:
    api:
        container_name: api-server
        build:
            context: ./apps/api
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        networks:
            backend:
                ipv4_address: 192.100.100.2
        depends_on:
            - auth
            - event
            - mongodb
            - redis

    auth:
        container_name: auth-server
        build:
            context: ./apps/auth
            dockerfile: Dockerfile
        expose:
            - '4000'
        networks:
            backend:
                ipv4_address: 192.100.100.3
        depends_on:
            - mongodb
            - redis

    event:
        container_name: event-server
        build:
            context: ./apps/event
            dockerfile: Dockerfile
        expose:
            - '5000'
        networks:
            backend:
                ipv4_address: 192.100.100.4
        depends_on:
            - mongodb
            - redis

    mongodb:
        image: mongo:4.4
        container_name: nexon-mongodb
        expose:
            - '27017'
        networks:
            backend:
                ipv4_address: 192.100.100.10
        volumes:
            - mongo_data:/data/db

    redis:
        image: redis:7
        container_name: nexon-redis
        expose:
            - '6379'
        networks:
            backend:
                ipv4_address: 192.100.100.11
        volumes:
            - redis_data:/data

volumes:
    mongo_data:
    redis_data:
