# apps/api/Dockerfile (auth, event도 동일한 방식)
FROM node:18-alpine

WORKDIR /usr/src/app

COPY ../../package*.json ./
COPY ../../tsconfig.base.json ./
COPY ../../nest-cli.json ./
COPY ../../libs ./libs
COPY ./ .

RUN npm install --force
RUN npm run build api

CMD ["sh", "-c", "cross-env mode=prod service=api node dist/apps/api/main.js"]
